### ISSUE TITLE
The pretrained model error

### ISSUE THREAD

**Issue by lumeihe** [antabangun/coex#10]
hello sir, I got the error like this :
If any possibility that the pretrained model you gave was  @wrong?
===================================
Traceback (most recent call last):
  File "/media/hy/DISK2/depth_estimate/6-Coex/demo.py", line 41, in <module>
    pose_ssstereo = Stereo.load_from_checkpoint(cfg['stereo_ckpt'],
  File "/home/hy/anaconda3/envs/leastereo/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 161, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/home/hy/anaconda3/envs/leastereo/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 203, in _load_model_state
    model = cls(**_cls_kwargs)
  File "/media/hy/DISK2/depth_estimate/6-Coex/stereo.py", line 44, in __init__
    self.stereo = load_class(
  File "/media/hy/DISK2/depth_estimate/6-Coex/models/stereo/CoEx.py", line 26, in __init__
    self.feature = Feature(self.cfg)
  File "/media/hy/DISK2/depth_estimate/6-Coex/models/stereo/submodules/feature.py", line 204, in __init__
    model = timm.create_model(self.type, pretrained=pretrained, features_only=True)
  File "/home/hy/anaconda3/envs/leastereo/lib/python3.8/site-packages/timm/models/factory.py", line 71, in create_model
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
  File "/home/hy/anaconda3/envs/leastereo/lib/python3.8/site-packages/timm/models/efficientnet.py", line 1335, in mobilenetv2_100
    model = _gen_mobilenet_v2('mobilenetv2_100', 1.0, pretrained=pretrained, **kwargs)
  File "/home/hy/anaconda3/envs/leastereo/lib/python3.8/site-packages/timm/models/efficientnet.py", line 766, in _gen_mobilenet_v2
    model = _create_effnet(variant, pretrained, **model_kwargs)
  File "/home/hy/anaconda3/envs/leastereo/lib/python3.8/site-packages/timm/models/efficientnet.py", line 629, in _create_effnet
    model = build_model_with_cfg(
  File "/home/hy/anaconda3/envs/leastereo/lib/python3.8/site-packages/timm/models/helpers.py", line 545, in build_model_with_cfg
    load_pretrained(
  File "/home/hy/anaconda3/envs/leastereo/lib/python3.8/site-packages/timm/models/helpers.py", line 245, in load_pretrained
    state_dict = load_state_dict_from_url(
  File "/home/hy/anaconda3/envs/leastereo/lib/python3.8/site-packages/torch/hub.py", line 595, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/hy/anaconda3/envs/leastereo/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/hy/anaconda3/envs/leastereo/lib/python3.8/site-packages/torch/serialization.py", line 938, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 139955 more bytes. The file might be corrupted.

**Comment by antabangun** [comment]
Hi,
I did not encounter the same error as this one. But I did encounter some error due to new updates in timm and pytorch-lightning packages. Perhaps this is related to your error.
I've now updated the environment.yml file to specify the working versions for the above packages. Could you try updating the conda environment, and let me know if the error still persist?

**Comment by antabangun** [comment]
I will be closing this issue due to inactivity
